Repository siemens/element, pull requests merged in 2025-07, with the labels that each got.

#171 docs(backdrop): add ux docs
  docs/patterns/images/backdrop.png
  mkdocs.yml
Labels: documentation

#167 docs(README): use absolute urls for links
  projects/element-translate-ng/README.md
  projects/native-charts-ng/README.md
Labels: documentation

#172 docs(loading-patterns): add ux docs
  docs/patterns/images/loading-global-progress-bar.png
  docs/patterns/images/loading-global-spinner.png
  docs/patterns/images/loading-inline-button.png
  docs/patterns/images/loading-inline.png
  docs/patterns/loading.md
  mkdocs.yml
Labels: documentation

#174 docs(notifications-patterns): add ux docs
  docs/patterns/images/notification-components.png
  docs/patterns/images/notification-management.png
  docs/patterns/images/notifications-anatomy.png
  docs/patterns/images/notifications-indicators.png
  docs/patterns/images/notifications-notification-center.png
  docs/patterns/images/notifications-overflow.png
  docs/patterns/images/notifications-popover-variants.png
  docs/patterns/images/notifications-popover.png
  docs/patterns/images/notifications-side-panel-actions.png
  docs/patterns/images/notifications-side-panel-groups-1.png
  docs/patterns/images/notifications-side-panel-groups.png
  docs/patterns/images/notifications-side-panel.png
  docs/patterns/images/notifications-unread-state.png
  docs/patterns/notifications.md
  mkdocs.yml
Labels: documentation

#175 chore(deps): update prettier to 3.6
  package-lock.json
  package.json
  projects/element-theme/src/styles/components/_datatable.scss
  projects/element-translate-ng/README.md
Labels: enhancement

#194 docs(shapes): update ux docs
  docs/fundamentals/images/shapes-rounded.png
  docs/fundamentals/shapes.md
Labels: documentation

#161 docs(tree-view): provide more clarity on usage of enableContextMenuButton
  projects/element-ng/tree-view/si-tree-view.component.ts
Labels: documentation

#197 docs(buttons): update ux images
  docs/components/buttons-menus/images/button-content.png
  docs/components/buttons-menus/images/button-link.png
Labels: documentation

#203 refactor(docs): update toast
  docs/components/status-notifications/images/toast-notification-usage-construction.png
  docs/components/status-notifications/images/toast-notification-usage-types.png
  docs/components/status-notifications/images/toast-notification-usage-variations.png
  docs/components/status-notifications/images/toast-notification.png
  docs/components/status-notifications/toast-notification.md
Labels: documentation

#201 docs(status-notifications): updated images and added caution and critical version
  docs/components/status-notifications/images/inline-notification-usage-actions.png
  docs/components/status-notifications/images/inline-notification-usage-construction.png
  docs/components/status-notifications/images/inline-notification-usage-variations.png
  docs/components/status-notifications/images/inline-notification.png
  docs/components/status-notifications/inline-notification.md
Labels: documentation

#210 docs(photo-uploader): update ux docs
  docs/components/forms-inputs/images/photo-upload-dialog-elemets.png
  docs/components/forms-inputs/images/photo-upload-elements.png
  docs/components/forms-inputs/images/photo-upload-shape.png
  docs/components/forms-inputs/images/photo-upload.png
  docs/components/forms-inputs/photo-upload.md
Labels: documentation

#218 docs(main-detail): update images
  docs/components/layout-navigation/images/main-detail-bulk-action.png
  docs/components/layout-navigation/images/main-detail-edit.png
  docs/components/layout-navigation/images/main-detail-filters-flow.png
  docs/components/layout-navigation/images/main-detail-global-actions.png
  docs/components/layout-navigation/images/main-detail.png
  docs/components/layout-navigation/main-detail-container.md
Labels: documentation

#220 docs(side-panel): update image
  docs/components/layout-navigation/images/side-panel.png
Labels: documentation

#202 docs(system-banner): update system banner images
  docs/components/status-notifications/images/system-banner-elements.png
  docs/components/status-notifications/images/system-banner-variants.png
  docs/components/status-notifications/images/system-banner.png
  docs/components/status-notifications/system-banner.md
Labels: documentation

#235 refactor: align module names
  projects/charts-ng/src/public-api.module.ts
  projects/live-preview/live-preview-routes.ts
  projects/live-preview/public-api.module.ts
  projects/native-charts-ng/src/public-api.module.ts
  src/app/app.config.ts
Labels: enhancement

#226 docs(status-bar): update status-bar component images
  docs/components/status-notifications/images/circle-status.png
  docs/components/status-notifications/images/status-bar-blink.png
  docs/components/status-notifications/images/status-bar-elements.png
  docs/components/status-notifications/images/status-bar-item.png
  docs/components/status-notifications/images/status-bar-responsive.png
  docs/components/status-notifications/images/status-bar-sizes.png
  docs/components/status-notifications/status-bar.md
Labels: documentation

#229 docs(popover): update popover component images
  docs/components/status-notifications/images/popover-content.png
  docs/components/status-notifications/images/popover-elements.png
  docs/components/status-notifications/images/popover-placement.png
  docs/components/status-notifications/images/popover.png
  docs/components/status-notifications/popover.md
Labels: documentation

#240 docs(empty-state): update empty-state component images
  docs/components/status-notifications/empty-state.md
  docs/components/status-notifications/images/empty-state-usage-construction.png
Labels: documentation

#225 docs(circle-status): update circle-status component images
  docs/components/status-notifications/circle-status.md
  docs/components/status-notifications/images/circle-status-badge.png
  docs/components/status-notifications/images/circle-status-in-out.png
  docs/components/status-notifications/images/circle-status-priority-symbols.png
  docs/components/status-notifications/images/circle-status-pulse.png
  docs/components/status-notifications/images/circle-status-row.png
  docs/components/status-notifications/images/circle-status-usage.png
  docs/components/status-notifications/images/circle-status-variation.png
Labels: documentation

#217 docs(vertical-navigation): update ux docs
  docs/components/layout-navigation/images/vertical-navigation-collapsed.png
  docs/components/layout-navigation/images/vertical-navigation-elements.png
  docs/components/layout-navigation/images/vertical-navigation.png
Labels: documentation

#212 docs(radio): update ux docs
  docs/components/forms-inputs/images/radio-button-label.png
  docs/components/forms-inputs/images/radio-button-states.png
  docs/components/forms-inputs/images/radio-usage-alignment.png
  docs/components/forms-inputs/images/radio-use-case.png
  docs/components/forms-inputs/radio.md
Labels: documentation

#206 docs(date-range-filter): update ux docs
  docs/components/forms-inputs/date-range-filter.md
  docs/components/forms-inputs/images/date-range-filter-advanced.png
  docs/components/forms-inputs/images/date-range-filter-default.png
  docs/components/forms-inputs/images/date-range-filter.png
Labels: documentation

#224 docs(wizard): update ux docs
  docs/components/layout-navigation/images/wizard-usage-button-placement.png
  docs/components/layout-navigation/images/wizard-usage-construction.png
  docs/components/layout-navigation/images/wizard-usage-steps.png
  docs/components/layout-navigation/images/wizard-vertical-divider.png
  docs/components/layout-navigation/images/wizard.png
  docs/components/layout-navigation/wizard.md
Labels: documentation

#205 docs(date-time): update ux images
  docs/components/forms-inputs/datepicker.md
  docs/components/forms-inputs/images/date-picker-anatomy.png
  docs/components/forms-inputs/images/date-range-picker.png
  docs/components/forms-inputs/images/date-time.png
  docs/components/forms-inputs/images/single-date-picker.png
  docs/components/forms-inputs/images/time-picker.png
Labels: documentation

#243 docs(tree): update ux docs
  docs/components/lists-tables-trees/images/tree-view-usage-construction.png
  docs/components/lists-tables-trees/images/tree-view-usage-vertical-navigation.png
  docs/components/lists-tables-trees/images/tree-view.png
  docs/components/lists-tables-trees/tree-view.md
Labels: documentation

#256 feat(translate): resolve error with new application unit test builder
  projects/element-ng/breadcrumb/si-breadcrumb.component.ts
  projects/element-ng/column-selection-dialog/si-column-selection-dialog.component.ts
  projects/element-ng/filtered-search/si-filtered-search.component.ts
  projects/element-ng/filtered-search/values/typeahead/si-filtered-search-typeahead.component.ts
  projects/element-ng/formly/fields/button/si-formly-button.component.spec.ts
  projects/element-ng/formly/fields/text/si-formly-text-display.component.spec.ts
  projects/element-ng/language-switcher/si-language-switcher.component.ts
  projects/element-ng/link/si-link.directive.spec.ts
  projects/element-ng/link/si-link.directive.ts
  projects/element-ng/localization/si-locale.service.ts
  projects/element-ng/phone-number/si-phone-number-input.component.ts
  projects/element-ng/status-bar/si-status-bar.component.ts
  projects/element-translate-ng/translate/index.ts
  projects/element-translate-ng/translate/si-localize.spec.ts
  projects/element-translate-ng/translate/si-localize.ts
  projects/element-translate-ng/translate/si-translate.inject.ts
  projects/element-translate-ng/translate/si-translate.module.ts
  projects/element-translate-ng/translate/si-translate.pipe.ts
  projects/element-translate-ng/translate/si-translate.service.ts
Labels: enhancement

#273 build(github): only run e2e summary on failure
  .github/workflows/build-and-test.yaml
Labels: enhancement

#250 docs(split-button): new component documented
  docs/components/buttons-menus/images/split-button-usage-construction.png
  docs/components/buttons-menus/images/split-button.png
  docs/components/buttons-menus/split-button.md
  docs/components/index.md
  mkdocs.yml
Labels: documentation

#269 docs(menu): update images and copy text to latest guideline
  docs/components/buttons-menus/images/menu-alternatives.png
  docs/components/buttons-menus/images/menu-elements.png
  docs/components/buttons-menus/images/menu.png
  docs/components/buttons-menus/menu.md
Labels: documentation

#276 docs(typeahead): add missing examples
  playwright/e2e/element-examples/si-typeahead.spec.ts
  playwright/snapshots/si-typeahead.spec.ts-snapshots/si-typeahead--si-typeahead-basic-element-examples-chromium-dark-linux.png
  playwright/snapshots/si-typeahead.spec.ts-snapshots/si-typeahead--si-typeahead-basic-element-examples-chromium-light-linux.png
  playwright/snapshots/si-typeahead.spec.ts-snapshots/si-typeahead--si-typeahead-basic.yaml
  playwright/snapshots/si-typeahead.spec.ts-snapshots/si-typeahead--si-typeahead-custom-element-examples-chromium-dark-linux.png
  playwright/snapshots/si-typeahead.spec.ts-snapshots/si-typeahead--si-typeahead-custom-element-examples-chromium-light-linux.png
  playwright/snapshots/si-typeahead.spec.ts-snapshots/si-typeahead--si-typeahead-custom.yaml
  src/app/examples/si-typeahead/si-typeahead-async.html
  src/app/examples/si-typeahead/si-typeahead-async.ts
  src/app/examples/si-typeahead/si-typeahead-basic.html
  src/app/examples/si-typeahead/si-typeahead-basic.ts
  src/app/examples/si-typeahead/si-typeahead-custom.html
  src/app/examples/si-typeahead/si-typeahead-custom.ts
  src/app/examples/si-typeahead/si-typeahead-onfocus-scrollable.html
  src/app/examples/si-typeahead/si-typeahead-onfocus-scrollable.ts
  src/app/examples/si-typeahead/si-typeahead-tokenized.html
  src/app/examples/si-typeahead/si-typeahead-tokenized.ts
Labels: enhancement

#281 docs(threshold): update threshold component
  docs/components/forms-inputs/images/threshold-usage-configuration.png
  docs/components/forms-inputs/images/threshold-usage-layout.png
  docs/components/forms-inputs/images/threshold-usage-number.png
  docs/components/forms-inputs/images/threshold-usage-specification.png
  docs/components/forms-inputs/images/threshold-usage-validation.png
  docs/components/forms-inputs/images/threshold.png
  docs/components/forms-inputs/threshold.md
Labels: documentation

#302 docs(colors): correct `$siemens-interactive-blue-500` color value
  docs/fundamentals/colors/color-palette.md
  docs/fundamentals/colors/ui-colors.md
Labels: documentation

#295 fix(photo-upload): remove padding from the sides for default preview
  projects/element-ng/photo-upload/si-photo-upload.component.scss
Labels: bug

#325 docs(colors): correct value of `interactive-blue-500`
  docs/fundamentals/colors/color-palette.md
  docs/fundamentals/colors/ui-colors.md
Labels: documentation

#343 docs(electron-titlebar): add missing example
  playwright/e2e/element-examples/static.spec.ts
  playwright/snapshots/static.spec.ts-snapshots/si-electron-titlebar--si-fixed-height-layout-side-panel-element-examples-chromium-dark-linux.png
  playwright/snapshots/static.spec.ts-snapshots/si-electron-titlebar--si-fixed-height-layout-side-panel-element-examples-chromium-light-linux.png
  playwright/snapshots/static.spec.ts-snapshots/si-electron-titlebar--si-fixed-height-layout-side-panel.yaml
  src/app/examples/si-electron-titlebar/si-fixed-height-layout-side-panel.html
  src/app/examples/si-electron-titlebar/si-fixed-height-layout-side-panel.ts
Labels: documentation

#364 build(release): use `release` instead of `maintenance` branches
  .releaserc.js
Labels: enhancement

#365 docs(contributing): use `release` instead of `maintenance`
  CONTRIBUTING.md
Labels: documentation

#339 feat(angular): update to Angular 20
  angular.json
  eslint.config.js
  package-lock.json
  package.json
  projects/charts-ng/package.json
  projects/charts-ng/tsconfig.lib.json
  projects/dashboards-demo/package.json
  projects/dashboards-demo/tsconfig.app.json
  projects/dashboards-demo/tsconfig.app.prod.json
  projects/dashboards-ng/package.json
  projects/dashboards-ng/src/components/web-component-wrapper/si-web-component-wrapper-base.component.ts
  projects/element-ng/column-selection-dialog/column-selection-editor/si-column-selection-editor.component.ts
  projects/element-ng/common/services/scrollbar-helper.service.ts
  projects/element-ng/common/services/text-measure.service.ts
  projects/element-ng/dashboard/si-dashboard.component.ts
  projects/element-ng/datepicker/components/si-month-selection.component.ts
  projects/element-ng/datepicker/components/si-year-selection.component.ts
  projects/element-ng/datepicker/si-calendar-button.component.ts
  projects/element-ng/datepicker/si-date-input.directive.ts
  projects/element-ng/datepicker/si-datepicker-overlay.component.ts
  projects/element-ng/datepicker/si-datepicker.directive.ts
  projects/element-ng/header-dropdown/si-header-dropdown-trigger.directive.ts
  projects/element-ng/header-dropdown/si-header-dropdown.component.ts
  projects/element-ng/ip-input/si-ip-input.directive.ts
  projects/element-ng/modal/si-modal.component.ts
  projects/element-ng/package.json
  projects/element-ng/popover-next/si-popover.component.ts
  projects/element-ng/shadow-root/si-shadow-root.directive.ts
  projects/element-ng/side-panel/si-side-panel.component.ts
  projects/element-ng/skip-links/skip-link.service.ts
  projects/element-ng/split/si-split.component.ts
  projects/element-ng/status-bar/si-status-bar.component.spec.ts
  projects/element-ng/tabs-next/si-tab-next-link.component.ts
  projects/element-ng/theme/si-theme.service.ts
  projects/element-ng/tour/si-tour.component.ts
  projects/element-ng/tour/si-tour.service.ts
  projects/element-ng/tree-view/si-tree-view-item/si-tree-view-item.component.ts
  projects/element-ng/typeahead/si-typeahead.directive.ts
  projects/element-translate-ng/ngx-translate/si-translate-ngxt.spec.ts
  projects/element-translate-ng/package.json
  projects/element-translate-ng/translate/si-translate.service.ts
  projects/live-preview/package.json
  projects/live-preview/tsconfig.lib.json
  projects/native-charts-ng/package.json
  src/tsconfig.app.json
  tsconfig.json
Labels: breaking-changes

#368 refactor(examples): drop duplicate card titles in si-card examples
  playwright/snapshots/static.spec.ts-snapshots/si-card--bootstrap-card-grid-element-examples-chromium-dark-linux.png
  playwright/snapshots/static.spec.ts-snapshots/si-card--bootstrap-card-grid-element-examples-chromium-light-linux.png
  playwright/snapshots/static.spec.ts-snapshots/si-card--bootstrap-card-grid.yaml
  playwright/snapshots/static.spec.ts-snapshots/si-card--bootstrap-card-group-element-examples-chromium-dark-linux.png
  playwright/snapshots/static.spec.ts-snapshots/si-card--bootstrap-card-group-element-examples-chromium-light-linux.png
  playwright/snapshots/static.spec.ts-snapshots/si-card--bootstrap-card-group.yaml
  src/app/examples/si-card/bootstrap-card-grid.html
  src/app/examples/si-card/bootstrap-card-group.html
Labels: enhancement

#381 build(github): pull request preview deployments
  .github/workflows/build-and-test.yaml
Labels: enhancement

#382 feat(charts/gauge): support custom value formatter
  projects/charts-ng/src/components/si-chart-gauge/si-chart-gauge.component.ts
Labels: enhancement

#420 build(github): remove unused dependencies from e2e merge report
  .github/workflows/build-and-test.yaml
Labels: enhancement

#434 feat(tooltip): support template context with tooltip template
  projects/element-ng/tooltip/si-tooltip.component.html
  projects/element-ng/tooltip/si-tooltip.component.ts
  projects/element-ng/tooltip/si-tooltip.directive.spec.ts
  projects/element-ng/tooltip/si-tooltip.directive.ts
  projects/element-ng/tooltip/si-tooltip.service.ts
Labels: enhancement

#418 refactor(tabs-next): fully rely on routing for link tabs
  projects/element-ng/tabs-next/si-tab-next-base.directive.ts
  projects/element-ng/tabs-next/si-tab-next-link.component.ts
  projects/element-ng/tabs-next/si-tab-next.component.ts
  projects/element-ng/tabs-next/si-tabset-next.component.ts
Labels: enhancement

#416 feat(form): drop form-item legacy mode
  playwright/e2e/element-examples/si-form-legacy.spec.ts
  playwright/snapshots/si-form-legacy.spec.ts-snapshots/si-form--si-form-legacy--large-element-examples-chromium-dark-linux.png
  playwright/snapshots/si-form-legacy.spec.ts-snapshots/si-form--si-form-legacy--large-element-examples-chromium-light-linux.png
  playwright/snapshots/si-form-legacy.spec.ts-snapshots/si-form--si-form-legacy--large-validated-element-examples-chromium-dark-linux.png
  playwright/snapshots/si-form-legacy.spec.ts-snapshots/si-form--si-form-legacy--large-validated-element-examples-chromium-light-linux.png
  playwright/snapshots/si-form-legacy.spec.ts-snapshots/si-form--si-form-legacy--large-validated.yaml
  playwright/snapshots/si-form-legacy.spec.ts-snapshots/si-form--si-form-legacy--large.yaml
  playwright/snapshots/si-form-legacy.spec.ts-snapshots/si-form--si-form-legacy-element-examples-chromium-dark-linux.png
  playwright/snapshots/si-form-legacy.spec.ts-snapshots/si-form--si-form-legacy-element-examples-chromium-light-linux.png
  playwright/snapshots/si-form-legacy.spec.ts-snapshots/si-form--si-form-legacy.yaml
  projects/element-ng/form/si-form-item/si-form-item.component.html
  projects/element-ng/form/si-form-item/si-form-item.component.ts
  projects/element-ng/form/si-form.spec.ts
  projects/element-ng/formly/fields/text/si-formly-text-display.component.html
  src/app/examples/si-form/si-form-legacy.html
  src/app/examples/si-form/si-form-legacy.ts
Labels: breaking-changes
