Repository siemens/element, pull requests merged in 2025-08, with the labels that each got.

#441 refactor(tabs-next): drop `SiTabsetNextComponent.deselect` event
  projects/element-ng/tabs-next/si-tab-next.component.ts
  projects/element-ng/tabs-next/si-tabset-next.component.ts
  src/app/examples/si-tabs/si-tabs-next-icons.html
  src/app/examples/si-tabs/si-tabs-next-icons.ts
  src/app/examples/si-tabs/si-tabs-next.html
  src/app/examples/si-tabs/si-tabs-next.ts
Labels: enhancement

#452 docs(ai-chat): update legal disclaimer
  docs/components/chat-messages/images/chat-input-elements.png
  docs/components/chat-messages/images/chat-input.png
  docs/patterns/ai/images/ai-chat-elements.png
  docs/patterns/ai/images/ai-chat-full-page.png
  docs/patterns/ai/images/ai-chat-max-width.png
  docs/patterns/ai/images/ai-chat-side-panel.png
  docs/patterns/ai/images/ai-chat.png
  docs/patterns/ai/images/ai-errors.png
  docs/patterns/ai/images/ai-icon-usage.png
  docs/patterns/ai/images/ai-initial-screen.png
  docs/patterns/ai/images/ai.png
Labels: documentation, ux

#361 refactor(typeahead): remove deprecations
  projects/element-ng/typeahead/si-typeahead.directive.ts
Labels: breaking-changes

#358 refactor(tree-view): remove deprecations
  projects/element-ng/tree-view/si-tree-view.component.ts
Labels: breaking-changes

#459 refactor(tabs-next): remove unused `activeTabIndex`
  projects/element-ng/tabs-next/si-tab-next.component.ts
  projects/element-ng/tabs-next/si-tabset-next.component.ts
Labels: enhancement

#357 refactor(split): remove deprecations
  projects/element-ng/split/si-split-part.component.ts
  projects/element-ng/split/si-split.component.spec.ts
Labels: breaking-changes

#469 refactor(native-charts-ng): split package into separate entrypoints
  projects/native-charts-ng/gauge/index.ts
  projects/native-charts-ng/gauge/ng-package.json
  projects/native-charts-ng/gauge/si-nchart-gauge.component.html
  projects/native-charts-ng/gauge/si-nchart-gauge.component.scss
  projects/native-charts-ng/gauge/si-nchart-gauge.component.ts
  projects/native-charts-ng/ng-package.json
  projects/native-charts-ng/public-api.module.ts
  projects/native-charts-ng/public-api.ts
  projects/native-charts-ng/utils/index.ts
  projects/native-charts-ng/utils/ng-package.json
  projects/native-charts-ng/utils/svg-math.ts
  src/tsconfig.app.prod.json
  tsconfig.json
Labels: enhancement

#478 build(github): use correct version pattern for aws-actions
  .github/workflows/build-and-test.yaml
Labels: bug

#388 fix(date-range-filter): stop automatic advanced mode toggle in input mode
  projects/element-ng/date-range-filter/si-date-range-filter.component.ts
Labels: bug

#470 refactor(typescript): use stricter path mappings
  projects/element-ng/datepicker/testing/si-datepicker.harness.ts
  projects/element-ng/testing/index.ts
  tsconfig.json
Labels: enhancement

#498 refactor(element-translate-ng): drop patching `$localize` globally
  projects/dashboards-demo/tsconfig.app.json
  projects/dashboards-demo/webcomponents/tsconfig.app.json
  projects/dashboards-demo/webcomponents/tsconfig.app.prod.json
  projects/dashboards-ng/tsconfig.json
  projects/dashboards-ng/tsconfig.lib.json
  projects/dashboards-ng/tsconfig.spec.json
  projects/element-ng/tsconfig.json
  projects/element-ng/tsconfig.lib.json
  projects/element-ng/tsconfig.spec.json
  projects/element-translate-ng/localize-types/index.d.ts
  projects/element-translate-ng/localize-types/index.ts
  projects/element-translate-ng/translate/index.ts
  projects/element-translate-ng/translate/si-localize.spec.ts
  projects/element-translate-ng/translate/si-localize.ts
  projects/element-translate-ng/translate/t.ts
Labels: enhancement

#539 feat(tree-view): remove `SiTreeViewComponent.disableFilledIcons` input
  playwright/snapshots/si-tree-view.spec.ts-snapshots/si-tree-view--si-tree-view-playground--base-tree-element-examples-chromium-dark-linux.png
  playwright/snapshots/si-tree-view.spec.ts-snapshots/si-tree-view--si-tree-view-playground--base-tree-element-examples-chromium-light-linux.png
  playwright/snapshots/si-tree-view.spec.ts-snapshots/si-tree-view--si-tree-view-playground--base-tree-with-checkbox-element-examples-chromium-dark-linux.png
  playwright/snapshots/si-tree-view.spec.ts-snapshots/si-tree-view--si-tree-view-playground--base-tree-with-checkbox-element-examples-chromium-light-linux.png
  playwright/snapshots/si-tree-view.spec.ts-snapshots/si-tree-view--si-tree-view-playground--base-tree-with-checkbox.yaml
  playwright/snapshots/si-tree-view.spec.ts-snapshots/si-tree-view--si-tree-view-playground--base-tree-with-data-field-2-element-examples-chromium-dark-linux.png
  playwright/snapshots/si-tree-view.spec.ts-snapshots/si-tree-view--si-tree-view-playground--base-tree-with-data-field-2-element-examples-chromium-light-linux.png
  playwright/snapshots/si-tree-view.spec.ts-snapshots/si-tree-view--si-tree-view-playground--base-tree-with-data-field-2.yaml
  playwright/snapshots/si-tree-view.spec.ts-snapshots/si-tree-view--si-tree-view-playground--base-tree.yaml
  playwright/snapshots/si-tree-view.spec.ts-snapshots/si-tree-view--si-tree-view-playground--expand-collapse-element-examples-chromium-dark-linux.png
  playwright/snapshots/si-tree-view.spec.ts-snapshots/si-tree-view--si-tree-view-playground--expand-collapse-element-examples-chromium-light-linux.png
  playwright/snapshots/si-tree-view.spec.ts-snapshots/si-tree-view--si-tree-view-playground--expand-collapse.yaml
  playwright/snapshots/si-tree-view.spec.ts-snapshots/si-tree-view--si-tree-view-playground--flat-tree-element-examples-chromium-dark-linux.png
  playwright/snapshots/si-tree-view.spec.ts-snapshots/si-tree-view--si-tree-view-playground--flat-tree-element-examples-chromium-light-linux.png
  playwright/snapshots/si-tree-view.spec.ts-snapshots/si-tree-view--si-tree-view-playground--flat-tree.yaml
  playwright/snapshots/si-tree-view.spec.ts-snapshots/si-tree-view--si-tree-view-playground--grouped-tree-element-examples-chromium-dark-linux.png
  playwright/snapshots/si-tree-view.spec.ts-snapshots/si-tree-view--si-tree-view-playground--grouped-tree-element-examples-chromium-light-linux.png
  playwright/snapshots/si-tree-view.spec.ts-snapshots/si-tree-view--si-tree-view-playground--grouped-tree.yaml
  playwright/snapshots/static.spec.ts-snapshots/si-tree-view--si-tree-view.yaml
  projects/element-ng/tree-view/si-tree-view-item/si-tree-view-item.component.html
  projects/element-ng/tree-view/si-tree-view-item/si-tree-view-item.component.ts
  projects/element-ng/tree-view/si-tree-view.component.spec.ts
  projects/element-ng/tree-view/si-tree-view.component.ts
  src/app/examples/si-tree-view/si-tree-view-playground.html
  src/app/examples/si-tree-view/si-tree-view-playground.ts
Labels: breaking-changes

#648 docs(help-patterns): update ux docs
  docs/patterns/help.md
  docs/patterns/images/help-contextual-elements.png
  docs/patterns/images/help-contextual-examples.png
  docs/patterns/images/help-general.png
  docs/patterns/images/help-tour.png
Labels: documentation, ux
