Repository siemens/element, pull requests merged in 2025-09, with the labels that each got.

#672 docs(landing-page): fix landing-page docs exemple
  docs/components/pages/landing-page.md
Labels: documentation

#700 docs(help-patterns): add link to help button
  docs/patterns/help.md
  mkdocs.yml
Labels: documentation, ux

#719 fix(navbar-vertical-item): align badge in collapse state correctly
  playwright/snapshots/navbar-vertical-legacy.spec.ts-snapshots/si-navbar-vertical--si-navbar-vertical-legacy--collapsed-element-examples-chromium-dark-linux.png
  playwright/snapshots/navbar-vertical-legacy.spec.ts-snapshots/si-navbar-vertical--si-navbar-vertical-legacy--collapsed-element-examples-chromium-light-linux.png
  playwright/snapshots/navbar-vertical-legacy.spec.ts-snapshots/si-navbar-vertical--si-navbar-vertical-legacy--collapsed-flyout-element-examples-chromium-dark-linux.png
  playwright/snapshots/navbar-vertical-legacy.spec.ts-snapshots/si-navbar-vertical--si-navbar-vertical-legacy--collapsed-flyout-element-examples-chromium-light-linux.png
  playwright/snapshots/navbar-vertical.spec.ts-snapshots/si-navbar-vertical--si-navbar-vertical--collapsed-element-examples-chromium-dark-linux.png
  playwright/snapshots/navbar-vertical.spec.ts-snapshots/si-navbar-vertical--si-navbar-vertical--collapsed-element-examples-chromium-light-linux.png
  playwright/snapshots/navbar-vertical.spec.ts-snapshots/si-navbar-vertical--si-navbar-vertical--collapsed-flyout-element-examples-chromium-dark-linux.png
  playwright/snapshots/navbar-vertical.spec.ts-snapshots/si-navbar-vertical--si-navbar-vertical--collapsed-flyout-element-examples-chromium-light-linux.png
  projects/element-ng/navbar-vertical/si-navbar-vertical-item.component.html
  projects/element-ng/navbar-vertical/si-navbar-vertical-item.component.scss
  projects/element-ng/navbar-vertical/si-navbar-vertical-item.component.spec.ts
  projects/element-ng/navbar-vertical/si-navbar-vertical-item.component.ts
Labels: bug

#706 chore(demo): make accordion with base-1 example better
  playwright/snapshots/static.spec.ts-snapshots/si-accordion--si-accordion-base-1-element-examples-chromium-dark-linux.png
  playwright/snapshots/static.spec.ts-snapshots/si-accordion--si-accordion-base-1-element-examples-chromium-light-linux.png
  src/app/examples/si-accordion/si-accordion-base-1.html
Labels: documentation

#724 chore(demo): fix checkbox classes for si-date-range-filter demo
  playwright/snapshots/si-date-range-filter.spec.ts-snapshots/si-date-range-filter--si-date-range-filter--mobile-element-examples-chromium-dark-linux.png
  playwright/snapshots/si-date-range-filter.spec.ts-snapshots/si-date-range-filter--si-date-range-filter--mobile-element-examples-chromium-light-linux.png
  playwright/snapshots/si-date-range-filter.spec.ts-snapshots/si-date-range-filter--si-date-range-filter--mobile-presets-element-examples-chromium-dark-linux.png
  playwright/snapshots/si-date-range-filter.spec.ts-snapshots/si-date-range-filter--si-date-range-filter--mobile-presets-element-examples-chromium-light-linux.png
  src/app/examples/si-date-range-filter/si-date-range-filter.html
Labels: enhancement

#712 docs(file-uploader): remove deprecated httpclientmodule import
  docs/components/forms-inputs/file-uploader.md
Labels: documentation

#729 fix(file-uploader): allow concurrent uploads in auto-upload mode
  projects/element-ng/file-uploader/si-file-uploader.component.ts
Labels: bug

#746 chore(readme): add npm badge
  README.md
Labels: enhancement

#769 docs: fix typos
  docs/components/buttons-menus/buttons.md
  docs/components/forms-inputs/checkbox.md
  docs/components/forms-inputs/forms.md
  docs/components/forms-inputs/input.md
  docs/components/forms-inputs/radio.md
  docs/components/status-notifications/avatar.md
  docs/fundamentals/layouts/overview.md
  docs/patterns/drag-and-drop.md
  docs/patterns/loading.md
Labels: documentation

#779 chore(package-lock): update datatable version
  package-lock.json
Labels: enhancement
